name: Daily Playwright Tests

on:
  schedule:
    - cron: '0 0 * * *'  # Executa todos os dias à meia-noite (UTC)
  workflow_dispatch:     # Permite executar o workflow manualmente

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14, 16, 18]  # Testa em diferentes versões do Node.js

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: npm install

    - name: Install Playwright browsers
      run: npx playwright install

    - name: Run Playwright tests
      run: npx playwright test
